name: Daily AWS Lambda Invocation

on:
  schedule:
    - cron: '0 0 * * *'  # This runs daily at midnight UTC
  workflow_dispatch:

jobs:
  invoke-lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Refers to the secret in GitHub
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Refers to the secret in GitHub
        aws-region: ${{ secrets.AWS_REGION }}  # Ensure region is supplied
        
    - name: Invoke Lambda function
      run: |
        aws lambda invoke \
          --function-name covid19-data-fetcher \
          --invocation-type Event \
          --payload '{}' \
          lambda_output.json

    - name: Show Lambda output
      run: cat lambda_output.json
